### ISSUE TITLE
Prevent Navigation Without Redmine Details

### ISSUE THREAD

**Issue by rp4rk** [rp4rk/tnt#6]
# Description

The user should not be able to navigate into the "Time Entries" section of the application until valid Redmine details are entered.

## Acceptance Criteria
- [ ] The user cannot navigate to other parts of the application until valid Redmine details have been entered.

**Comment by d1wilko** [comment]
https://github.com/rp4rk/tnt/pull/18 half fixes this - still need to disable URL navigation

**Comment by d1wilko** [comment]
https://github.com/rp4rk/tnt/pull/20 should fix this completely
